root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = ""
  cmd = "make build_debug"
  delay = 0
  exclude_dir = ["src/sql"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = "/go/bin/dlv exec dist/api --headless --api-version 2 --continue --accept-multiclient --listen \"0.0.0.0:18000\""
  include_dir = ["src"]
  include_ext = ["go", "tpl", "tmpl"]
  include_file = []
  kill_delay = "2s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = true
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
