version: '3.9'
services:
  roach1:
    image: cockroachdb/cockroach:latest
    volumes:
      - ROACH1_DATA:/cockroach/cockroach-data
      - ./db-dev-init/:/docker-entrypoint-initdb.d
    ports:
      - 26257:26257
      - 8080:8080
    command:
      - start-single-node
      - --insecure

  db-migrate-and-seed:
    depends_on:
      - roach1
    build:
      context: .
      dockerfile: Dockerfile_migrate
    volumes:
      - ".:/build"
    environment:
      - APP_NAME=migrate-and-seed
      - PG_MIGRATION_DB=postgresql://donation_mgmt_migrator@roach1:26257/donationsdb?schema=donations
      - DB_HOST=roach1
      - DB_PORT=26257
      - DB_USER=donation_mgmt_app
      - DB_PASSWORD=
      - DB_NAME=donationsdb
      - DB_SCHEMA=donations

  donation-mgmt:
    depends_on:
      - roach1
    build:
      context: .
      target: build
      dockerfile: Dockerfile
    volumes:
      - ".:/build"
    ports:
      - "8000:8000"
      - "18000:18000"
    environment:
      - DB_HOST=roach1
      - DB_PORT=26257
      - DB_USER=donation_mgmt_app
      - DB_PASSWORD=
      - DB_NAME=donationsdb
      - DB_SCHEMA=donations
      - GCP_PROJECT_ID=donation-mgmt-stg
      - HTTP_AUTH=devheader
      - GCP_SA_JSON_PATH=/build/credentials/gcp-sa.json
    entrypoint: "/build/scripts/watch.sh"

volumes:
  ROACH1_DATA:
