services:
  postgres:
    image: postgres:17.2-alpine3.20
    volumes:
      - POSTGRES_DATA:/var/lib/postgresql/data
      - ./db-dev-init/:/docker-entrypoint-initdb.d
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: superuser

  db-migrate-and-seed:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile_migrate
    volumes:
      - ".:/build"
    environment:
      - APP_NAME=migrate-and-seed
      - PG_MIGRATION_DB=postgresql://donation_mgmt_migrator:MvGfJjzmxzLOYQjhF9i1fvq9dQemZmGvJdFVIbAsb37nopG4gR3GE4D4nOf3xWvX@postgres:5432/donationsdb?schema=donations
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=donation_mgmt_migrator
      - DB_PASSWORD=MvGfJjzmxzLOYQjhF9i1fvq9dQemZmGvJdFVIbAsb37nopG4gR3GE4D4nOf3xWvX
      - DB_NAME=donationsdb
      - DB_SCHEMA=donations

  donation-mgmt:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    develop:
      watch:
        - action: sync+restart
          path: ./src
          target: /build/src
        - action: sync+restart
          path: ./sqlc
          target: /build/sqlc
        - action: sync+restart
          path: ./prisma
          target: /build/prisma
        - action: rebuild
          path: go.mod
    ports:
      - "8000:8000"
      - "18000:18000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=donation_mgmt_app
      - DB_PASSWORD=yq2REWv0iD8nepOe1BFskFwPDgn69mFbjt2q3hzmB8THCLtteXKHMws1teMKLIu7
      - DB_NAME=donationsdb
      - DB_SCHEMA=donations
      - GCP_PROJECT_ID=donation-mgmt-stg
      - HTTP_AUTH=devheader
      - GCP_SA_JSON_PATH=/build/credentials/gcp-sa.json

volumes:
  POSTGRES_DATA:
