version: '3.9'
services:
  donation-mgmt:
    build:
      context: .
      target: build
      dockerfile: Dockerfile
    volumes:
      - ".:/build"
    ports:
      - "8000:8000"
    entrypoint: "/build/scripts/watch.sh"
