-- CreateTable
CREATE TABLE "roles" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "capabilities" STRING[],
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "archived_at" TIMESTAMPTZ,

    CONSTRAINT "roles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "scoped_user_roles" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "subject" STRING NOT NULL,
    "role_id" INT8 NOT NULL,
    "organization_id" INT8 NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "scoped_user_roles_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "global_user_roles" (
    "id" INT8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "subject" STRING NOT NULL,
    "role_id" INT8 NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "global_user_roles_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "roles_name_key" ON "roles"("name");

-- CreateIndex
CREATE UNIQUE INDEX "scoped_user_roles_subject_organization_id_key" ON "scoped_user_roles"("subject", "organization_id");

-- CreateIndex
CREATE UNIQUE INDEX "global_user_roles_subject_key" ON "global_user_roles"("subject");

-- AddForeignKey
ALTER TABLE "scoped_user_roles" ADD CONSTRAINT "scoped_user_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "scoped_user_roles" ADD CONSTRAINT "scoped_user_roles_organization_id_fkey" FOREIGN KEY ("organization_id") REFERENCES "organizations"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "global_user_roles" ADD CONSTRAINT "global_user_roles_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
