CREATE SCHEMA IF NOT EXISTS donations;
GRANT USAGE ON SCHEMA donations TO donations_ro;

-- Grant permissions to relevant roles on future created resources
ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO donations_ro;

ALTER DEFAULT PRIVILEGES GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO donations_rw;
ALTER DEFAULT PRIVILEGES GRANT USAGE, SELECT ON SEQUENCES TO donations_rw;
ALTER DEFAULT PRIVILEGES GRANT EXECUTE ON FUNCTIONS TO donations_rw;

ALTER DEFAULT PRIVILEGES GRANT TRUNCATE ON TABLES TO donations_maintenance;
ALTER DEFAULT PRIVILEGES GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO donations_maintenance;
